

services:
  cpu-stress:
    image: node:20-alpine
    container_name: cpu-stress-container
    
    volumes:
      - ./stress.js:/app/stress.js
    
    command: node /app/stress.js
    
    # PIN TO CORE 0
#    cpuset: "0"
    
    # NATIVE COMPOSE CPU AND MEMORY LIMITS
#    cpus: 0.5
#    cpu_shares: 256  
    cpu_period: 100000
    cpu_quota: 50000
